# Author: Leon Miao
# Module (backbone, head): [n_repeat, module_name, *args]
  # Conv: [c_in, c_out, k, s, act, bias]
  # Linear: [c_in, c_out, act, bias]
  # Pool: [glb, k, s]
  # ResNetLayer: [c_in, c_hidden, n_blocks, downsample]
  # VggBlock: [c_in, c_out, n_layers, k, s]
backbone:
  [
    [1, ConvBN, [3, 64, 7, 2]],
    [1, MaxPool, [False, 3, 2]],
    [1, ResNetLayer, [64, 64, 3, False]],
    [1, ResNetLayer, [256, 128, 4, True]],
    [1, ResNetLayer, [512, 256, 23, True]],
    [1, ResNetLayer, [1024, 512, 3, True]],
  ]
head:
  [
    [1, AvgPool, [True]],
    [1, Flatten, [1]],
    [1, Linear, [2048, 28, False, True]]
  ]